# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: "Build the project binaries"
    cmds:
      - go build -o ./bin/citadel ./cmd/citadel
      - go build -o ./bin/citadel-cli ./cmd/citadel-cli

  build:distros:
    desc: "Build multiple distributions with goreleaser"
    cmds:
      - goreleaser build -f .goreleaser.yml --rm-dist --skip-validate

  server:
    desc: "Run the citadel server"
    cmds:
      - ./bin/citadel

  gen:
    desc: "Generate updated project files"
    cmds:
      - goa gen github.com/brittonhayes/citadel/design
