name: CI

on: [ pull_request ]

jobs:
  reviewdog:
    name: review
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1

      - name: misspell
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--disable-all -E misspell"
          tool_name: misspell
          level: info

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build executables
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist --skip-validate
